/**
 * Behaviour library — the observable calling behaviours described in the two
 * ICC reference documents. Frameworks pick behaviours from here and assign
 * them to sections. Wording of source notes is kept close to the documents.
 *
 * T = CSC_Call_Template_Jun15.pdf  ("ICC Benchmark" team report + script template)
 * X = XinNi_ICC_Report_v2.pdf      ("ICC CSC Framework v1" individual report)
 */
import type { Behaviour, DetectorId, SourceRef } from '@/types/framework';

const T = (note: string): SourceRef => ({ document: 'CSC_Call_Template_Jun15.pdf', note });
const X = (note: string): SourceRef => ({ document: 'XinNi_ICC_Report_v2.pdf', note });

type LibraryEntry = Omit<Behaviour, 'weight' | 'id'>;

export const BEHAVIOURS: Record<DetectorId, LibraryEntry> = {
  // ─── Introduction / Opening ─────────────────────────────────────────────
  warm_greeting: {
    label: 'Warm greeting',
    detector: 'warm_greeting',
    strengthTitle: 'Opened with a warm greeting',
    gapTitle: 'No warm greeting at the start',
    whyItMatters: 'The first seconds set the tone for the whole call.',
    coachingTip: 'Open with a friendly hello before anything else — keep it warm and conversational, not scripted.',
    practiceAction: 'Rehearse a warm, natural 30-second opener.',
    issueCode: 'intro_greeting',
    lessonId: 'introduction',
    source: T('Criteria "Warm greeting, name, brand, purpose"; script: "Keep it warm and conversational — not scripted"'),
  },
  agent_name: {
    label: 'States own name',
    detector: 'agent_name',
    strengthTitle: 'Introduced themself by name',
    gapTitle: 'Did not state own name',
    whyItMatters: 'A name makes the call personal and builds trust from the first line.',
    coachingTip: 'Say your name clearly in the first sentence.',
    practiceAction: 'Standardise the opener: name + brand + reason for calling.',
    issueCode: 'intro_inconsistent',
    lessonId: 'introduction',
    source: T('Script step 1: "State your name + brand name clearly"'),
  },
  brand_name: {
    label: 'States brand name (U.R. Klinik)',
    detector: 'brand_name',
    strengthTitle: 'Stated the U.R. Klinik brand clearly',
    gapTitle: 'Brand name not stated in the introduction',
    whyItMatters: 'Leads enquire with many clinics; hearing the brand anchors who is calling and why.',
    coachingTip: 'Mention "U.R. Klinik" in your first sentence, right after your name.',
    practiceAction: 'Standardise the opener: name + brand + reason for calling.',
    issueCode: 'intro_inconsistent',
    lessonId: 'introduction',
    source: T('Irene gap: "Introduction unclear — no brand name stated"; script: "State your name + brand name clearly"'),
  },
  call_purpose: {
    label: "Mentions the lead's enquiry / reason for call",
    detector: 'call_purpose',
    strengthTitle: "Linked the call to the lead's enquiry",
    gapTitle: 'Reason for the call was not made clear',
    whyItMatters: 'Reminding the lead of their own enquiry makes the call expected rather than cold.',
    coachingTip: 'Mention the enquiry or advert the lead responded to, so they remember why you are calling.',
    practiceAction: 'Practise a one-line reason-for-call that references the lead source.',
    issueCode: 'intro_inconsistent',
    lessonId: 'introduction',
    source: T('Script step 1: "Mention the lead\'s enquiry/reason for call"'),
  },
  customer_name: {
    label: "Uses the customer's name",
    detector: 'customer_name',
    strengthTitle: "Used the customer's name",
    gapTitle: "Customer's name was not used",
    whyItMatters: 'Using the name personalises the conversation and builds rapport early.',
    coachingTip: "Use the customer's name at least once in the opening.",
    practiceAction: 'Prepare a 5-second warm opener (name + light compliment).',
    issueCode: 'intro_personalisation',
    lessonId: 'introduction',
    source: X('Section A gap: "Never used the customer\'s name and offered no personal icebreaker or compliment"'),
  },
  icebreaker_compliment: {
    label: 'Personal icebreaker or compliment',
    detector: 'icebreaker_compliment',
    strengthTitle: 'Added a personal icebreaker',
    gapTitle: 'No icebreaker before business questions',
    whyItMatters: 'A small personal touch turns a sales call into a conversation.',
    coachingTip: 'Prepare a 5-second warm opener (name + light compliment) to use as soon as the line is clear.',
    practiceAction: 'Prepare a 5-second warm opener (name + light compliment).',
    issueCode: 'intro_personalisation',
    lessonId: 'introduction',
    source: X('Section A coaching tip: "Prepare a 5-second warm opener (name + light compliment)"'),
  },
  connection_recovery: {
    label: 'Quick recovery from connection issues',
    detector: 'connection_recovery',
    strengthTitle: 'No time lost to connection issues',
    gapTitle: 'Opening time lost to connection issues',
    whyItMatters: 'Repeated "can you hear me?" exchanges eat into the critical first 30 seconds.',
    coachingTip: 'Have a warm, personalised re-opener ready to use the moment the audio clears.',
    practiceAction: 'Role-play opening recovery after audio/connection issues.',
    issueCode: 'intro_connection',
    lessonId: 'introduction',
    source: X('Focus area 5: "Recover Faster From Opening Connection Issues"'),
  },

  // ─── Discovery ──────────────────────────────────────────────────────────
  concern_probe: {
    label: 'Probes the skin concern with open questions',
    detector: 'concern_probe',
    strengthTitle: "Asked directly about the customer's skin concern",
    gapTitle: "Customer's main concern was not explored",
    whyItMatters: 'Everything that follows — the solution, the offer, the close — depends on knowing the real concern.',
    coachingTip: 'Ask an open question and let the customer describe THEIR issue in their own words.',
    practiceAction: 'Practise three open discovery questions.',
    issueCode: 'discovery_shallow',
    lessonId: 'discovery',
    source: T('Criteria "Probing skin concerns, doubts, lifestyle"; script: "Ask open questions — let them describe THEIR issue"'),
  },
  clarify_vague: {
    label: 'Clarifies vague descriptions',
    detector: 'clarify_vague',
    strengthTitle: 'Clarified a vague description',
    gapTitle: 'Vague descriptions were not clarified',
    whyItMatters: 'Words like "sensitive" can mean redness, peeling or stinging — each needs a different answer.',
    coachingTip: 'When the customer uses a vague word, ask what it looks or feels like (e.g. redness? peeling?).',
    practiceAction: 'Practise follow-up clarification questions.',
    issueCode: 'discovery_shallow',
    lessonId: 'discovery',
    source: X('Section B did well: "Followed up on the vague word 敏感 (sensitive) by asking the customer to clarify: redness? peeling?"'),
  },
  mirror_concern: {
    label: "Mirrors the customer's concern",
    detector: 'mirror_concern',
    strengthTitle: "Mirrored the customer's words back",
    gapTitle: "Customer's concern was not restated",
    whyItMatters: 'Restating the concern confirms active listening and makes the customer feel understood.',
    coachingTip: "Restate the customer's frustration in full (not only the symptom) before moving on.",
    practiceAction: 'Practise restating concern + emotion before pitching.',
    issueCode: 'discovery_shallow',
    lessonId: 'discovery',
    source: X('Section B did well: "Mirrored the customer\'s own words back … confirming she was actively listening"'),
  },
  duration_probe: {
    label: 'Probes how long the problem has existed',
    detector: 'duration_probe',
    strengthTitle: 'Asked how long the concern has lasted',
    gapTitle: 'Duration / timeline of the concern not pinned down',
    whyItMatters: 'The timeline helps explain the root cause and sets realistic expectations.',
    coachingTip: 'Ask: "How long have you had this problem?"',
    practiceAction: 'Add a duration question to every discovery.',
    issueCode: 'discovery_shallow',
    lessonId: 'discovery',
    source: T('Script step 2: "Probe duration: \'Have long have you had this problem?\'" · X Section B gap: "timeline … was not pinned down clearly"'),
  },
  previous_treatment: {
    label: "Asks what they've tried before",
    detector: 'previous_treatment',
    strengthTitle: 'Explored previous treatment history',
    gapTitle: 'Previous treatments were not explored',
    whyItMatters: 'Past treatments reveal expectations, doubts and possible causes.',
    coachingTip: "Ask what they've tried before and how it went.",
    practiceAction: 'Add a treatment-history question to every discovery.',
    issueCode: 'discovery_shallow',
    lessonId: 'discovery',
    source: T('Script step 2: "Ask what they\'ve tried before"'),
  },
  lifestyle: {
    label: 'Explores lifestyle / skincare habits',
    detector: 'lifestyle',
    strengthTitle: 'Explored lifestyle and skincare habits',
    gapTitle: 'Lifestyle and skincare habits not explored',
    whyItMatters: 'Routine, sun exposure and habits are often the missing link to root-cause education.',
    coachingTip: 'After identifying the main concern, add one lifestyle question (sun exposure, current routine) before moving to solutions.',
    practiceAction: 'Add one lifestyle question before every solution explanation.',
    issueCode: 'discovery_lifestyle',
    lessonId: 'discovery',
    source: T('Criteria "Probing skin concerns, doubts, lifestyle" · X Section B gap: "Never asked about daily lifestyle or skincare habits"'),
  },
  emotional_pain: {
    label: 'Surfaces the emotional pain / doubts',
    detector: 'emotional_pain',
    strengthTitle: 'Surfaced how the concern affects the customer',
    gapTitle: 'Emotional impact of the concern not surfaced',
    whyItMatters: 'Customers act on how a problem makes them feel, not only on the symptom.',
    coachingTip: 'Ask how the concern affects them day to day — confidence, make-up, photos.',
    practiceAction: 'Practise one emotional-impact question.',
    issueCode: 'discovery_emotion',
    lessonId: 'discovery',
    source: T('Script step 2: "Surface the emotional pain"'),
  },

  // ─── Product knowledge / Solution ───────────────────────────────────────
  ai_skin_analysis: {
    label: 'Mentions AI Skin Analysis',
    detector: 'ai_skin_analysis',
    strengthTitle: 'Introduced the AI Skin Analysis',
    gapTitle: 'AI Skin Analysis not mentioned',
    whyItMatters: 'The AI Skin Analysis is the key differentiator — it shows the clinic diagnoses before recommending.',
    coachingTip: 'Always mention the AI Skin Analysis as the first step to understand their skin properly.',
    practiceAction: 'Make the AI Skin Analysis a mandatory line in every product explanation.',
    issueCode: 'product_ai_scan',
    lessonId: 'product',
    source: T('Script step 3: "AI Skin Analysis = key differentiator — always mention!" · Irene gap: "No AI Skin Analysis mention"'),
  },
  light_system: {
    label: 'Explains the 3-light system',
    detector: 'light_system',
    strengthTitle: 'Explained the 3-light therapy system',
    gapTitle: '3-light system not explained',
    whyItMatters: 'The light system is the core of the treatment the lead is being invited to try.',
    coachingTip: 'Name the 3-light therapy and connect it to their concern.',
    practiceAction: 'Practise a 20-second 3-light system explanation.',
    issueCode: 'product_light_system',
    lessonId: 'product',
    source: T('Criteria "3-light system, AI scan, differentiation" · Irene gap: "No 3-light system explained"'),
  },
  light_purpose: {
    label: 'Describes light types by purpose',
    detector: 'light_purpose',
    strengthTitle: 'Described the lights by what they do',
    gapTitle: 'Lights named, but not explained by purpose',
    whyItMatters: 'Purpose ("this light calms redness") is more convincing than a product name.',
    coachingTip: 'Mention the 3 light types by purpose, not only by name.',
    practiceAction: 'Practise explaining each light by the problem it solves.',
    issueCode: 'product_light_system',
    lessonId: 'product',
    source: T('Script step 3: "Mention 3 light types by purpose (not just by name)"'),
  },
  concern_to_solution: {
    label: 'Connects their concern → specific solution',
    detector: 'concern_to_solution',
    strengthTitle: "Connected the customer's concern to the solution",
    gapTitle: "Solution not connected to the customer's concern",
    whyItMatters: 'A recommendation feels relevant only when it answers the concern the customer described.',
    coachingTip: 'Link the treatment directly back to the concern they described ("because you mentioned…").',
    practiceAction: 'Practise "because you mentioned X, we recommend Y" bridges.',
    issueCode: 'product_connection',
    lessonId: 'product',
    source: T('Script step 3: "Connect their specific concern → specific solution"'),
  },
  root_cause: {
    label: 'Explains the root cause',
    detector: 'root_cause',
    strengthTitle: 'Explained why the skin behaves this way',
    gapTitle: 'Root cause was not explained',
    whyItMatters: 'Connecting cause to solution builds far more conviction than listing services.',
    coachingTip: 'Before naming the treatment, spend one sentence on WHY this is happening to their skin.',
    practiceAction: 'Practise a one-sentence root-cause explanation before naming the package.',
    issueCode: 'product_root_cause',
    lessonId: 'product',
    source: X('Section C gap: "Never explained the underlying root cause"; focus area 3: "Turn the Solution Pitch Into a Root-Cause Story"'),
  },
  differentiation_testimonial: {
    label: 'Differentiation / testimonials',
    detector: 'differentiation_testimonial',
    strengthTitle: 'Referenced results or what makes the clinic different',
    gapTitle: 'No differentiation or testimonial shared',
    whyItMatters: 'Real results from similar customers reduce doubt.',
    coachingTip: 'Reference a testimonial or similar customer result where possible.',
    practiceAction: 'Prepare one short customer success story per common concern.',
    issueCode: 'product_differentiation',
    lessonId: 'product',
    source: T('Criteria "…differentiation"; script step 3: "Reference testimonials if possible"'),
  },

  // ─── Clinic & doctor credibility (Framework v1 only) ────────────────────
  clinic_experience: {
    label: 'Clinic experience',
    detector: 'clinic_experience',
    strengthTitle: "Mentioned the clinic's years of experience",
    gapTitle: 'Clinic experience not mentioned',
    whyItMatters: 'Experience is a quick trust signal.',
    coachingTip: "Mention the clinic's years of experience with this concern.",
    practiceAction: 'Add one credibility line when introducing the clinic.',
    issueCode: 'credibility_clinic',
    lessonId: 'product',
    source: X('Section D did well: "Mentioned the clinic\'s 12 years of experience"'),
  },
  clinic_branches: {
    label: 'Branch network / nearest outlet',
    detector: 'clinic_branches',
    strengthTitle: 'Mentioned branches and the nearest outlet',
    gapTitle: 'Nearest outlet / branches not mentioned',
    whyItMatters: 'A convenient, named location makes visiting feel easy.',
    coachingTip: "Name the outlet closest to the customer's area.",
    practiceAction: 'Always name the nearest outlet during the call.',
    issueCode: 'credibility_clinic',
    lessonId: 'product',
    source: X('Section D did well: "Cited 9 branches across Malaysia and named the closest one"'),
  },
  doctor_credibility: {
    label: 'Doctor / specialist credibility line',
    detector: 'doctor_credibility',
    strengthTitle: 'Credited a doctor / specialist',
    gapTitle: 'No doctor or specialist mentioned',
    whyItMatters: 'A doctor reviewing results converts technology into perceived medical authority.',
    coachingTip: 'Add one sentence naming the reviewing doctor/specialist by role whenever the AI scan is introduced.',
    practiceAction: 'Add a doctor/specialist credibility line whenever the AI skin scan is introduced.',
    issueCode: 'credibility_doctor',
    lessonId: 'product',
    source: X('Focus area 4: "Add a Doctor / Specialist Credibility Line"'),
  },

  // ─── Objection handling ─────────────────────────────────────────────────
  no_obligation: {
    label: 'Reassures hesitation (no commitment)',
    detector: 'no_obligation',
    conditional: 'customer_hesitation',
    strengthTitle: 'Reassured the customer there is no commitment',
    gapTitle: 'Hesitation was not reassured',
    whyItMatters: 'Removing the fear of commitment makes the first visit an easy yes.',
    coachingTip: "If hesitant: 'You're not committing to anything, just come and let the doctor take a look.'",
    practiceAction: 'Rehearse the no-commitment reassurance line.',
    issueCode: 'objection_reassurance',
    lessonId: 'objection',
    source: T('Script step 4: "If hesitant: \'You\'re not committing to anything, just come and let the doctor take a look\'"'),
  },
  trial_risk_reduction: {
    label: 'Frames the trial as low-risk',
    detector: 'trial_risk_reduction',
    strengthTitle: 'Framed the trial as a low-risk first step',
    gapTitle: 'Trial not framed as a low-risk first step',
    whyItMatters: 'A low-cost trial removes financial risk before a bigger commitment.',
    coachingTip: 'Position the trial as a small, safe first step.',
    practiceAction: 'Practise positioning the trial as risk-free.',
    issueCode: 'objection_reassurance',
    lessonId: 'objection',
    source: X('Section E did well: "Framed the low-cost trial as a way to remove financial risk"'),
  },
  empathy: {
    label: 'Empathy',
    detector: 'empathy',
    strengthTitle: 'Showed empathy for the customer',
    gapTitle: "Customer's frustration was not acknowledged",
    whyItMatters: 'Empathy before pitching lowers resistance.',
    coachingTip: 'When a customer signals frustration, name it out loud first ("No wonder you feel worried…").',
    practiceAction: 'Practise acknowledging frustration before pitching.',
    issueCode: 'rapport_empathy',
    lessonId: 'rapport',
    source: T('Rapport & Tone criteria "Natural flow, empathy, confidence" · X Section E coaching: "empathy before pitching lowers resistance"'),
  },
  hesitation_incentive: {
    label: 'Offers a reason to act when the customer hedges',
    detector: 'hesitation_incentive',
    conditional: 'customer_hesitation',
    strengthTitle: 'Turned hesitation into a reason to act',
    gapTitle: 'No incentive offered when the customer hesitated',
    whyItMatters: '"Consider first" usually means no booking unless there is a concrete reason to act now.',
    coachingTip: 'When the customer hedges, bring in the gift and deadline as a concrete reason to book today.',
    practiceAction: 'Practise responding to "I\'ll think about it" with the offer + a slot.',
    issueCode: 'objection_hesitation',
    lessonId: 'objection',
    source: X('Section E gap: "When the customer hedged (考虑一下), no specific incentive was offered"'),
  },

  // ─── Urgency & offer ────────────────────────────────────────────────────
  promo_deadline: {
    label: '2-week promotional deadline',
    detector: 'promo_deadline',
    strengthTitle: 'Mentioned the promotional deadline',
    gapTitle: '2-week promotional deadline not mentioned',
    whyItMatters: 'Mentioning the deadline creates urgency — described in the reference as the #1 booking driver.',
    coachingTip: 'ALWAYS mention the 2-week deadline when presenting the offer.',
    practiceAction: 'Make the 2-week deadline a mandatory line in every offer.',
    issueCode: 'urgency_deadline',
    lessonId: 'urgency',
    source: T('Universal gap: "No one mentions the 2-week promotional deadline" — "Mentioning the deadline creates urgency — the #1 booking driver"'),
  },
  skincare_gift: {
    label: 'Free skincare gift',
    detector: 'skincare_gift',
    strengthTitle: 'Offered the free skincare gift',
    gapTitle: 'Free skincare gift not offered',
    whyItMatters: 'The gift is a concrete reason to act NOW, not "next week".',
    coachingTip: 'Name the free skincare gift clearly when you ask for the booking.',
    practiceAction: 'Add the free skincare gift as a mandatory line in every trial-offer pitch.',
    issueCode: 'urgency_gift',
    lessonId: 'urgency',
    source: T('Universal gap: "No one offers the free skincare gift at close" · X: "The 2-week free skincare gift was never mentioned"'),
  },
  limited_slots: {
    label: 'Limited-slot / scarcity cue',
    detector: 'limited_slots',
    strengthTitle: 'Used a limited-slot cue',
    gapTitle: 'No limited-slot framing',
    whyItMatters: 'A clear scarcity cue gives the customer a reason not to wait.',
    coachingTip: 'Add a limited-slot cue (e.g. only a few slots each week) to the offer line.',
    practiceAction: 'Script a fixed one-line urgency close: gift + limited-slot cue.',
    issueCode: 'urgency_scarcity',
    lessonId: 'urgency',
    source: X('Section F gap: "No specific deadline or limited-slot framing was clearly delivered"'),
  },
  clear_offer: {
    label: 'Clear, specific offer',
    detector: 'clear_offer',
    strengthTitle: 'Presented a clear, specific offer',
    gapTitle: 'Offer was unclear or not stated',
    whyItMatters: 'A concrete, repeatable offer line survives even a bad connection.',
    coachingTip: 'State the offer in one clear sentence: what they get, the price, and until when.',
    practiceAction: 'Rehearse the offer line until it is word-perfect.',
    issueCode: 'urgency_offer_unclear',
    lessonId: 'urgency',
    source: X('Section F gap: "The incentive language was mumbled/garbled"; T Xin Ni strength: "Offered RM399 package with AI scan + consultation"'),
  },

  // ─── Closing ────────────────────────────────────────────────────────────
  availability_probe: {
    label: "Asks about the customer's availability",
    detector: 'availability_probe',
    strengthTitle: "Asked about the customer's availability",
    gapTitle: 'No attempt to find a suitable slot',
    whyItMatters: 'Finding a slot is the bridge from interest to a booking.',
    coachingTip: 'Move from interest to scheduling — but offer specific options rather than an open question.',
    practiceAction: 'Practise moving from interest to scheduling.',
    issueCode: 'close_no_attempt',
    lessonId: 'closing',
    source: X('Section G did well: "Attempted to find a matching slot by asking about the customer\'s days off"'),
  },
  two_options: {
    label: 'Gives 2 specific date/time options',
    detector: 'two_options',
    strengthTitle: 'Offered two specific appointment options',
    gapTitle: "Didn't offer 2 specific date/time options",
    whyItMatters: 'Two specific choices are easier to say yes to than an open "when are you free?".',
    coachingTip: "Give 2 specific options — don't ask an open 'when are you free'.",
    practiceAction: 'Script and rehearse a two-option closing question.',
    issueCode: 'close_no_options',
    lessonId: 'closing',
    source: T('Script step 4: "Give 2 specific options — don\'t ask open \'when are you free\'"'),
  },
  appointment_confirmed: {
    label: 'Confirms a specific appointment',
    detector: 'appointment_confirmed',
    strengthTitle: 'Confirmed a specific appointment date & time',
    gapTitle: 'Specific appointment not confirmed',
    whyItMatters: "Always end with a confirmed slot — 'Consider first' = no booking.",
    coachingTip: 'Ask for the date and time directly, confirm it back to the customer, and only then say goodbye.',
    practiceAction: 'Script and rehearse a fixed closing line that asks for a specific date/time before the call ends.',
    issueCode: 'close_no_appointment',
    lessonId: 'closing',
    source: T('Criteria "Specific date/time…"; script: "Confirm the appointment before hanging up!"; universal gap: "No specific date/time confirmed on call"'),
  },
  recap_next_steps: {
    label: 'Recaps next steps',
    detector: 'recap_next_steps',
    strengthTitle: 'Recapped the next steps for the visit',
    gapTitle: 'No recap of next steps',
    whyItMatters: 'Setting expectations for the visit and a reminder touchpoint protects the booking.',
    coachingTip: 'Recap the slot, what happens at the visit, and when you will send a reminder.',
    practiceAction: 'Practise a 10-second booking recap.',
    issueCode: 'close_no_recap',
    lessonId: 'closing',
    source: X('Section G gap: "No recap of next steps was given"'),
  },
  no_handoff_close: {
    label: 'Owns the close (no hand-off)',
    detector: 'no_handoff_close',
    strengthTitle: 'Owned the close personally',
    gapTitle: 'Close handed off to a colleague',
    whyItMatters: 'Deferring the decision to a colleague loses momentum on a warm call.',
    coachingTip: "Never end a warm call with \"I'll pass you to someone else.\" Lock the booking first, then loop in a colleague.",
    practiceAction: 'Never defer the booking ask to a colleague.',
    issueCode: 'close_handoff',
    lessonId: 'closing',
    source: X('Section G gap: "Closed with 我會安排一位高級同事跟你談 (a senior will follow up) — handing off the close"'),
  },

  // ─── Rapport & tone ─────────────────────────────────────────────────────
  natural_flow: {
    label: 'Natural, two-way conversation',
    detector: 'natural_flow',
    strengthTitle: 'Kept a natural, two-way conversation',
    gapTitle: 'Conversation felt one-sided',
    whyItMatters: 'A natural flow keeps the lead engaged instead of listening to a script.',
    coachingTip: 'Pause after each explanation and invite the customer to respond.',
    practiceAction: 'Practise shorter explanations with check-in questions.',
    issueCode: 'rapport_flow',
    lessonId: 'rapport',
    source: T('Rapport & Tone criteria "Natural flow, empathy, confidence"'),
  },
  confidence: {
    label: 'Confident recommendations',
    detector: 'confidence',
    strengthTitle: 'Sounded confident and clear',
    gapTitle: 'Recommendations lacked confidence',
    whyItMatters: 'Customers follow a consultant who sounds sure of the recommendation.',
    coachingTip: 'Use clear recommendation language ("I recommend…", "the best first step is…") and fewer fillers.',
    practiceAction: 'Record yourself and cut fillers from the recommendation.',
    issueCode: 'rapport_confidence',
    lessonId: 'rapport',
    source: T('Rapport & Tone criteria "Natural flow, empathy, confidence"; Irene strength: "natural, confident tone"'),
  },
};

/** Build a framework behaviour from the library with a weight. */
export function pick(detector: DetectorId, weight = 1, idPrefix = ''): Behaviour {
  return { ...BEHAVIOURS[detector], id: `${idPrefix}${detector}`, weight };
}
